import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { MARKETING_BY_APPLIANCE_ID } from "./marketing-map";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const storefrontRoot = path.join(__dirname, "..");
const defaultOsRoot = path.join(storefrontRoot, "..", "curxor-os");
const osRoot = process.env.CURXOR_OS_ROOT ?? defaultOsRoot;
const outputPath = path.join(storefrontRoot, "src/lib/generated/appliance-sync.ts");

type VersionFile = {
  version: string;
  channel?: string;
};

type OotbApp = {
  id: string;
  name: string;
  description: string;
};

async function loadOotbApps(): Promise<OotbApp[]> {
  const modulePath = path.join(
    osRoot,
    "pillar-4-dashboard/lib/ootb-apps.ts"
  );

  if (!fs.existsSync(modulePath)) {
    throw new Error(`Missing appliance source: ${modulePath}`);
  }

  const moduleUrl = `${pathToFileURL(modulePath).href}?sync=${Date.now()}`;
  const imported = await import(moduleUrl);
  return [...imported.OOTB_APPS] as OotbApp[];
}

function loadVersion(): VersionFile {
  const versionPath = path.join(osRoot, "version.json");

  if (!fs.existsSync(versionPath)) {
    throw new Error(`Missing appliance version file: ${versionPath}`);
  }

  return JSON.parse(fs.readFileSync(versionPath, "utf8")) as VersionFile;
}

function pathToFileURL(filePath: string): URL {
  const resolved = path.resolve(filePath);
  return new URL(`file:///${resolved.replace(/\\/g, "/")}`);
}

function buildGeneratedSource(
  apps: Array<{
    id: string;
    applianceId: string;
    name: string;
    description: string;
    icon: string;
  }>,
  version: VersionFile
): string {
  const syncedAt = new Date().toISOString();

  return `// AUTO-GENERATED by scripts/sync-appliance.ts — do not edit manually.
// Source: ${path.relative(storefrontRoot, osRoot).replace(/\\/g, "/")}

export const applianceVersion = ${JSON.stringify(version.version)} as const;
export const applianceChannel = ${JSON.stringify(version.channel ?? "stable")} as const;
export const applianceSyncedAt = ${JSON.stringify(syncedAt)} as const;

export const apps = ${JSON.stringify(apps, null, 2)} as const;

export type StorefrontApp = (typeof apps)[number];
`;
}

async function main() {
  const version = loadVersion();
  const ootbApps = await loadOotbApps();

  const apps = ootbApps
    .map((app) => {
      const marketing =
        MARKETING_BY_APPLIANCE_ID[
          app.id as keyof typeof MARKETING_BY_APPLIANCE_ID
        ];

      if (!marketing) {
        throw new Error(`Missing marketing map for appliance app id: ${app.id}`);
      }

      return {
        id: marketing.storefrontId,
        applianceId: app.id,
        name: app.name,
        description: app.description,
        icon: marketing.icon,
        sortOrder: marketing.sortOrder ?? 999,
      };
    })
    .sort((a, b) => a.sortOrder - b.sortOrder)
    .map(({ sortOrder: _sortOrder, ...app }) => app);

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, buildGeneratedSource(apps, version), "utf8");

  console.log(
    `Synced ${apps.length} apps @ v${version.version} from ${osRoot}`
  );
  console.log(`→ ${path.relative(storefrontRoot, outputPath)}`);
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);

  if (message.includes("Missing appliance")) {
    console.warn(`[sync-appliance] Skipped: ${message}`);
    console.warn("[sync-appliance] Using committed src/lib/generated/appliance-sync.ts");
    process.exit(0);
  }

  console.error("[sync-appliance] Failed:", error);
  process.exit(1);
});
