import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const storefrontRoot = path.join(__dirname, "..");
const defaultOsRoot = path.join(storefrontRoot, "..", "curxor-os");
const osRoot = process.env.CURXOR_OS_ROOT ?? defaultOsRoot;

const entriesPath = path.join(storefrontRoot, "data/changelog-entries.json");
const outputPath = path.join(
  storefrontRoot,
  "src/lib/generated/changelog-sync.ts"
);

type VersionFile = {
  version: string;
  channel?: string;
};

type ChangelogEntry = {
  version: string;
  date: string;
  channel: string;
  highlights: string[];
};

function loadVersion(): VersionFile {
  const versionPath = path.join(osRoot, "version.json");
  if (!fs.existsSync(versionPath)) {
    throw new Error(`Missing appliance version file: ${versionPath}`);
  }
  return JSON.parse(fs.readFileSync(versionPath, "utf8")) as VersionFile;
}

function loadReleaseNotes(version: string): string[] | null {
  const notesPath = path.join(osRoot, "release-notes.json");
  if (!fs.existsSync(notesPath)) return null;

  const parsed = JSON.parse(fs.readFileSync(notesPath, "utf8")) as Record<
    string,
    { highlights?: string[] }
  >;
  const entry = parsed[version];
  if (!entry?.highlights?.length) return null;
  return entry.highlights;
}

function loadEntries(): ChangelogEntry[] {
  if (!fs.existsSync(entriesPath)) {
    return [];
  }
  const raw = JSON.parse(fs.readFileSync(entriesPath, "utf8")) as ChangelogEntry[];
  if (!Array.isArray(raw)) {
    throw new Error("data/changelog-entries.json must be a JSON array");
  }
  return raw;
}

function compareVersions(a: string, b: string): number {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i += 1) {
    const diff = (pa[i] ?? 0) - (pb[i] ?? 0);
    if (diff !== 0) return diff;
  }
  return 0;
}

function todayIsoDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function ensureCurrentVersionEntry(
  entries: ChangelogEntry[],
  version: VersionFile
): { entries: ChangelogEntry[]; appended: boolean } {
  const exists = entries.some((entry) => entry.version === version.version);
  if (exists) {
    return { entries, appended: false };
  }

  const releaseHighlights = loadReleaseNotes(version.version);
  const highlights =
    releaseHighlights ??
    [
      `CurXor OS ${version.version} — synced from version.json`,
      "Add release highlights in data/changelog-entries.json or curxor-os/release-notes.json",
    ];

  const nextEntry: ChangelogEntry = {
    version: version.version,
    date: todayIsoDate(),
    channel: version.channel ?? "stable",
    highlights,
  };

  const next = [...entries, nextEntry].sort((a, b) =>
    compareVersions(b.version, a.version)
  );

  fs.mkdirSync(path.dirname(entriesPath), { recursive: true });
  fs.writeFileSync(entriesPath, `${JSON.stringify(next, null, 2)}\n`, "utf8");

  console.log(
    `[sync-changelog] Appended v${version.version} to data/changelog-entries.json`
  );

  return { entries: next, appended: true };
}

function buildGeneratedSource(entries: ChangelogEntry[], version: VersionFile): string {
  const syncedAt = new Date().toISOString();
  return `// AUTO-GENERATED by scripts/sync-changelog.ts — do not edit manually.

export const changelogMeta = {
  version: ${JSON.stringify(version.version)} as const,
  channel: ${JSON.stringify(version.channel ?? "stable")} as const,
  syncedAt: ${JSON.stringify(syncedAt)} as const,
} as const;

export const changelogEntries = ${JSON.stringify(entries, null, 2)} as const;

export type ChangelogEntry = (typeof changelogEntries)[number];
`;
}

export function syncChangelog(): void {
  const version = loadVersion();
  let entries = loadEntries();
  const { entries: syncedEntries, appended } = ensureCurrentVersionEntry(
    entries,
    version
  );
  entries = syncedEntries.sort((a, b) => compareVersions(b.version, a.version));

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, buildGeneratedSource(entries, version), "utf8");

  console.log(
    `[sync-changelog] Wrote ${entries.length} entries @ v${version.version}${
      appended ? " (new entry auto-appended)" : ""
    }`
  );
  console.log(`→ ${path.relative(storefrontRoot, outputPath)}`);
}

const isDirectRun =
  process.argv[1] &&
  path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));

if (isDirectRun) {
  syncChangelog();
}
